fos_rest:
  param_fetcher_listener: true
  body_listener: true
  format_listener:
    enabled: true
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
      - { path: '^/', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
  versioning: true
  view:
    view_response_listener:
      enabled: true
#      force: true
    formats:
      json: true
  serializer:
    serialize_null: true